// Custom shader file for gm_construct.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

gm_construct/AEF36852FDDAC166C858559B171033FD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3680BD343CC8AB5FF8BF21D38AAD6EAA
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0009.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/28046C1A422FC8A4F594442EA4B2EE04
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3CE04FBE945FBA17192912EC1EB67108
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3A9857D70DD417A6E26BC5B8645680C0
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/61FE6412ACFB8D1F83BC34EDB5E9E6B0
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3DB1C2B656089719B4D11FF3BF24CEF6
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/47F754877F39E45D6F384EEF86A9E5C6
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_ground.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E683446E5DBC02ABDA5EB4EAAD58D0BD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/C51BA0B6717F57F118A24541FE54A2CA
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7011CBEC9C2F1D160E073598E82F6AD6
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/913D03A99C5232003805CF7729548E67
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7B032EB8A6AC0C2CFC97A95F6A66AB82
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/278BBF41E98C23D053B82B49D0CCC059
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B6D19746658E7DF47FDEFD4FA735D935
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1CFCCA15CB99B4762C47A401362436B1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B8DEA063A2D154960B89574C3802FE78
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/skip.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/EE908ECDD92C142C70C1FA8E8DD6AD8E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall003a_construct.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/35E73113229F4B8E4162819DBCB5D7B2
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall003a_construct.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/C70B6C9889FFD6C424E7E57686530703
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall003a_construct.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/9CB33E212A3551A4DE274794E256A95C
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0011.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0850773E9C9320E9A892932E8B519F6E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A876868EB6DA4F6ED4B12E36AC22C485
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/F7F6518333D0B11BB7F942E8F412564E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0014.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/57B99848AA5B5BA37658A842056B2E71
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0013.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E5CE7C0616AA8ECEAB824AC5D1B9BF93
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E660D8FE059081DF7B3BD1169F04EA5F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A28339202397EB261CB81221CA8D9040
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/06796FE8CCA889FEF02203A28E0DA861
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/15A111575F39ED641C648AC94FF2DBD8
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/CC4393A8CA27289EADCEE3A74C4191FD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_top.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/9ED0BB0B436B52D76DBC7B4985D21D91
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0009.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D46D4F99C052E2B366B9ABAEE34A37B0
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0014.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/051ACD977B2289AB526C2D3BDE15CC59
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0BFC0926718E44581FB8D92A995A039F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0013.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/02F6776FCEBEE742107364873AF641C1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1673815AE3AEC7D6BCC91F2C30807B21
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/92257DFB1B4740AB461F2FA59BF85AE9
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0012.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/68F34ECFA49C7383FBF55A82CB2841F4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0011.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/C764057EB1557DCB689AAF1F6C97E238
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B2D40E47869CB274313ADBE45EF8E623
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/CA2632B2FF62D081D006CD48A3BECC06
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1312049DBB5CB85079E822393CB69C5A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FC1AEBFAACBFE758E0B833E88980330B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B34476E71E6AE7381DE7FD12948BFBCD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/783CD896F2BF7555A355EE0A32ED6585
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/wall_bottom.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/10FA67A722557B7B5A17AC3B009BFCA1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2A28A0D0ACABBB82429225FDA12730E3
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/5536C37430D381546E7BED4C82D88B4E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FE130A87B9932722FA0F404632DCA422
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/8E6EF73439911FF684F4A7A851FDE06A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/AD79223C381A832E9B8FA833C4A7CF0E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/05C9C26A86410865078CC98D6886C429
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_concrete_floor.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1A1448C98E2A2CC39CCF3617ABB14793
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/708E1E5215B7657EAEEF077FABAC5F69
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0011.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/CF8D8EE9A83C0C0D081D0FCBF9EEEA71
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/5476DAF5D71FA16D78160060386CF091
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/6387D2D44B072F327D0ABBCEBD7EFF93
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/60D2FDCA3FE8C5E3A052D729CF13D251
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/24A4BFDF000E283A3B5E0D50AC9FC4D4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/6A15AB2D73BDBE2A27E3C5118AE1D250
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/36ED5D1180741E6D2C1A1122E6C56162
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A35B4052794FE708A2EC113AE8A5140A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0010.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall022c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1BAED92CE95A7A66C5E54B1C562ED089
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/146BAB198D9CC59192B226959C3BC8E5
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/684B0D8579828AC80D446745DD8EFF03
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/CDC802A341D22A7D2DEF899463DCC4A3
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A55F864D01B4FA0E84099C8581E409C2
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/31CB184C555313628E49C4428E1D6A56
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/98BC24CC0960AA824412FA6FAE901CBC
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/8F8A81D59A57DE7FBA40D3028861A9C8
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2250AB046A5BB4B8F90BD2A69076F522
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/EB07B6E05DC7FD3C68924D07731B4276
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0009.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/C6EA957124316AB1EE4D197126D2CC06
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FB47F56818EF963BB402668882F42A36
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A2DB0E871C750212602AD841C5B66867
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterwall016a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/58CCDFEB3DDC729D2E27E94C2C6EA428
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7F225E10BD85B41568CDF62A48737ED5
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FDBEC025389556FAADA0C27B21DE159B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/4F57EA4ECA344ED4A87F689E90AF7B74
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D22F7F7542052AE0BA7E0C7DB4BAA81F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/76E6F96F57E6CE07977DA8BE8C642289
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/4397E349FC8464B1C1AC367307576E56
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/BACAC2F44EC100AAAAA1931028179075
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/693E1FF65D03CAADC0726B653C235CDD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/dev/dev_measuregeneric01b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/87EAC09E0DE1DD5735E4A166600C7F15
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/dev/dev_measuregeneric01b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A64F2263269716F2F4DAEF15063935D7
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/plasticceiling002a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1F6F5AA690B5A704113E34B4A76E7D90
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/plasticceiling002a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/F66863CA1FABCF315529D81C69739FC1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0015.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/plasticceiling002a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/9BDB9850C423BF317925CE0EDD93CE8B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor026a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7E1C72AF7E4D65D8D1790A876EF1AFB7
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor008a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B7BFE78F6553C831DDA927F3C32D0946
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013o.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/F40215C8BAF44CE4498E446B3A8BCC23
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013o.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/93DDE8BB90691FE8CC475AA6CB6CDCA1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013o.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/8AD01635349A4C3E61AD8CFD18E73047
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013o.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/01081BC3385246418D4759E9FA597040
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013o.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/954EC35C494078928B981F3EAD1A080A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/22D3BF966F890680A29835089F98D34B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/4D4CB802B495CC73089E3A00404D1961
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D53A88A81E384E0D1B104377194C4AB1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/48CE5B46D68F68320CB0188532D1D128
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/582CA2073DF9397C00AD9C7B62D58A30
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/039AD397345E76F6FC955B4A8CA6CC41
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/779D61467311138D9C8D50EB35BF370D
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2754A6632B341D9AA24A30DA3E56998E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B0B67ED4A41C116AF9AA90AB30B512AE
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E61DDEAFA36379C6F1B94C592F0D261F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/735D7D86F568CDF26E24A24B3D03FF64
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/519B735E411C1BE5E0A1002E34267DB3
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/DD11A04DFB315E40F2A29F0748E52195
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/224ADAABD0D6E59312AA5B360CC67E71
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/81F6A25AEC13497E6C318574790640CD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7ECA553794706E678DF27988AB62AB77
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/4E34183E62CE7EA48684095BA9D1A82A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/DD09A9CFB5A73F0968525DD5E5A1BC5C
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/79CB24142934AD5E65FB325A5E0DFB38
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/16A108AC1B72A8DD66E2D05B6A9BB2C5
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1A8BE7C3476E8832511717393FF01B60
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/9CC40C0A27C0058E58B652719EBD36B9
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FD359577C502FAF7446B619BA4D03A44
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/EC8FFB75C49F146B322860C4697E445A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3474E5A557E9F443F8130F27462B97E4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D6C5CF221D439B23ADA1C001EEF6A01D
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0D5F55419B91F232F08E86DEBE93BA9F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/46746B947C9D7886887F5EB011633DB7
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0003.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2C3A0C0100E7ACD4E6087756F93D3275
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/50D804C70FF14AC0E2E5C3740DB94413
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0012.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/41C4D29A8F0ADF1BCEBE9C67AA39A90A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0009.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/7DCD50BA19BE114A8DB2884A2CA67424
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/329D6BE0B16057C9D6FADC9D7C6F4354
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0E9264B8331F67C6D6DE894187E05CBB
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0010.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/AD66F6F996D51EB8403918930075E845
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/DB812AD9A13D64AA0B3FB74190FFEE06
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0013.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0831362ACDB58358BDA58AFFBBF7657E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/EBD5E594F2DFF49B3D1B28C0CD0B8B91
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E8BE7DFD0718E969E8377C99DDE78460
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/5A11E1AFA3353C4EB3A2ADA17FF5EED0
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0011.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/0DCAB90A1C1C5F6FC206C524489A8479
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling005a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/36FC73C5913DA9C5527C21C5521FAFBD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010g.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/EE231010BEF1805D3F07F6E7AB38716C
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010g.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/37ED866B50DA1178ADDDDD1812F37132
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007m.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/685837F41AC33A3337C64E7E8B8F1218
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007m.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/401B73F79847EC8794128329EB042B3E
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007l.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/26C2A41428E001A4DDA4315C0EEAD53F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007l.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E679C329F30D85FE665DBFFA03A632B4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/86ECCF8044E6D3DC439EE206E5711370
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/3C96980058E003E213F1EE5900AE8C39
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/78C714F824513CF9AAB68CD7F8C772C1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007i.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/BDB4669E3F8628A7993FF4883C13CCF5
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007i.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/02A0C2D6B92A1BA4BA8E59A37942F98C
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/2B31174E62A19DCCA190CA7F6A9C88C4
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/A5E0E157D7AD0F483A9F259BA9D8050F
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template007a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/386DB057DB7734C5283875363CF8BF72
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template006b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/EF0EBB76E2B9DC565A7C6A6FD104B474
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template010a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/8B4B0B74C59B327708647756F1CC0675
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0011.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/D4B6A631DEE8A17E37BD7078D9B5672C
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/041E3DBF325EC46E0EFA6BC44182F1A9
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0007.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/9914F91D97151EEE40372F2763493975
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0006.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1AB87872E8C89F0B8789515D06B967DB
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0009.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1E8613B734D91BBDEF0435FECEBB9F11
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0012.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/1E14423F669780455F8A37AF2BBC9453
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0010.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass-sand_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/ABA7C45B39F68D14861C8082D210B0D1
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/metalcrate002d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/ADC97E055B2DC3B11C248186502FF6C6
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013h.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/22AA0C69E7C00AD2120B18B3AE53733A
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013j.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/115E0B759E1C89BC511F0E11B1EF948D
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretestair005a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/68A2C27DA8F66E41FA50170CDD754647
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/construct_credits.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/FF2193BEC50D31D096D848C321002755
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall053e.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/083C48EDAFDFE6CDB3125D11654E6452
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/building_template013m.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/B56972E91AA97B126D38F95978F57DDD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0008.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/color_room.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/03F10454D789421260456D7EE219F1AE
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0009.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/color_room.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/39B9EFBBC2F3538F24C4E310D003230B
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0005.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/color_room.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/E0CD134421E490361D5284EDDBF1E342
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/building_template/roof_template001a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/DB167DB5D256E7F850C913C806F08FFD
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0004.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/props/doorbutton002a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_construct/535141C7E9C95CD0B5B507953C959974
{ // Q3Map2 defaulted
	{
		map maps/gm_construct/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/plaster/plasterceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}


// Shaders to force nomipmaps flag on external lightmap images:

maps/gm_construct/nomipmaps0
{
	nomipmaps
	{
		animmap .0042 maps/gm_construct/lm_0000.tga maps/gm_construct/lm_0001.tga maps/gm_construct/lm_0002.tga maps/gm_construct/lm_0003.tga maps/gm_construct/lm_0004.tga maps/gm_construct/lm_0005.tga maps/gm_construct/lm_0006.tga maps/gm_construct/lm_0007.tga
	}
	{
		animmap .0042 maps/gm_construct/lm_0008.tga maps/gm_construct/lm_0009.tga maps/gm_construct/lm_0010.tga maps/gm_construct/lm_0011.tga maps/gm_construct/lm_0012.tga maps/gm_construct/lm_0013.tga maps/gm_construct/lm_0014.tga maps/gm_construct/lm_0015.tga
	}
}

