// Custom shader file for gm_flatgrass.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

gm_flatgrass/B4B1ABB5EB6449ACE75F8BA2F10DB727
{ // Q3Map2 defaulted
	{
		map maps/gm_flatgrass/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_flatgrass/DF320C6E6652881866D0FBBAB8F50063
{ // Q3Map2 defaulted
	{
		map maps/gm_flatgrass/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_flatgrass/2B6CDFA9D18DF98B4609650BEF5222E6
{ // Q3Map2 defaulted
	{
		map maps/gm_flatgrass/lm_0001.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concretefloor028a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_flatgrass/0EC2C836FCC13688A94D0616A9AD2A98
{ // Q3Map2 defaulted
	{
		map maps/gm_flatgrass/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall003a_construct.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_flatgrass/CF242901B128A3543642236440543ADE
{ // Q3Map2 defaulted
	{
		map maps/gm_flatgrass/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/brick/brickwall053d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_flatgrass/694B1A539A52FAE904D6052C31880BFF
{ // Q3Map2 defaulted
	{
		map maps/gm_flatgrass/lm_0000.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/concrete/concreteceiling003a.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

gm_flatgrass/6D255DE9D3721C03C2C374F271480B00
{ // Q3Map2 defaulted
	{
		map maps/gm_flatgrass/lm_0002.tga
		tcgen lightmap
		rgbGen identity
	}
	q3map_styleMarker
	{
		map textures/gm_construct/grass_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}


// Shaders to force nomipmaps flag on external lightmap images:

maps/gm_flatgrass/nomipmaps0
{
	nomipmaps
	{
		animmap .0042 maps/gm_flatgrass/lm_0000.tga maps/gm_flatgrass/lm_0001.tga maps/gm_flatgrass/lm_0002.tga
	}
}

